#!/bin/bash
case "$1" in
    aspm)      echo "$2" > /sys/module/pcie_aspm/parameters/policy ;;
    wifi)      /usr/bin/iw dev wlan0 set power_save "$2" ;;
    bluetooth)
        case "$2" in
            off) /usr/bin/rfkill block bluetooth ;;
            on)  /usr/bin/rfkill unblock bluetooth ;;
        esac
        ;;
esac
